### PR TITLE
feat: add hardcoded requiredETHFee to 100%

### PR DESCRIPTION
**Pull request by yashdesu**
#### Checklist

**I agree to the following :-**

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/WebXDAO/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by KukretiShubham — APPROVED** [review]
LGTM

**Comment by aggre** [comment]
@yashdesu Sorry, my bad! The code `utils.parseUnits(new BigNumber(opt.price).times(opt.fee.percentage).toFixed()).toString()` reminded me that `requiredETHFee` is an absolute value.

So, I think the correct value is `utils.parseUnits(opt.price.toString()).toString()`.

**Comment by aggre** [comment]
@yashdesu The purpose of this change was to prevent users from experiencing staking, and I found that the `requiredETHFee` change did not accomplish that... Sorry!

let me explain it:
- Since `requiredETHFee` is used as an argument in the actual transaction, if this value differs from the contract's expected value, the transaction will fail.
- `requiredETHFee` is calculated based on `opt.fee.percentage` and `opt.price`. `opt.fee.percentage` and `opt.price` are set in the membership edit page, and its value is also recorded in the contract. So if the values of `opt.fee.percentage` and `opt.price` and `requiredETHFee` are different, the transaction will fail.

Therefore, instead of overriding `requiredETHFee`, we should set `opt.fee.percentage` to `1` in the membership edit page. This will cause the contract state to match the UI state and the transaction to succeed.

**Comment by aggre** [comment]
Good change!

I'll add one more change to use `1` as percentage for all existing memberships as well.

**Pull request closed without merging**
